apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: disney-ai-plus

resources:
  - namespace.yaml
  - service-accounts.yaml
  - api-configmap.yaml
  - api-secrets.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-network-policy.yaml
  - web-configmap.yaml
  - web-secrets.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-network-policy.yaml
  - db-secrets.yaml
  - db-statefulset.yaml
  - db-service.yaml
  - db-network-policy.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - service-monitors.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/version: "1.0.0"
    includeSelectors: false
