apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: disney-ai-plus
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: disney-ai-plus
data:
  NODE_ENV: "production"
  PORT: "3000"
  API_URL: "http://api:80"
  NEXT_PUBLIC_API_URL: "http://api:80"
